services:
  mysql:
    image: mysql:8.0
    container_name: restaurant_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_mgt
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./TeamHATS_Complete_Database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  flask_app:
    build: .
    container_name: restaurant_flask
    ports:
      - "5001:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: database_mgt
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  mysql_data: